version: "3.7"
services:
  tournamentml-app:
    build:
      context: ./
      dockerfile: Dockerfile.prod
    image: tournamentml-app-prod
    container_name: tournamentml-app-prod
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - .env:/var/www/.env # Only mount .env for environment configurations
    networks:
      - my-networks

  tournamentml-nginx:
    build:
      context: ./
      dockerfile: Dockerfile.nginx
    image: tournamentml-nginx-prod
    container_name: tournamentml-nginx-prod
    restart: unless-stopped
    ports:
      - 8022:80
    networks:
      - my-networks
    depends_on:
      - tournamentml-app

networks:
  my-networks:
    driver: bridge
    name: my-networks
    external: true
